<?php

/**
 * 業務 フロント用 基底クラス
 *
 *
 * @package magicweapon
 * @link http://www.grid-works-guild.net/MagicWeapon/ MagicWeapon
 * @access  public
 * @author  Michiaki Wuzawa <wuzawa@m-fr.net>
 **/

require_once('common/base_model_sample_base.inc');

abstract class base_model_sample_front_base extends base_model_sample_base {

/**
 * 設定
 *
 * @access public
 */
public function initialize() {
}


} // end of class

